import {
  Hero,
  Navbar,
  Featured,
  Section,
  AreYouReady,
  Footer,
} from "@/components";
import Testimonial from "@/components/Testimonial";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";

const sections = [
  {
    id: 1,
    subHeading: "Analytics",
    heading: "built-in analytics to trach your NFTs",
    desc: "Use our built-in analytics dashboard to pull valuable insights and monitor the value of your Krypto portfolio over time",
    button: "View Our Pricing",
    img: "image_1.png",
  },
  {
    id: 2,
    subHeading: "Get Our App",
    heading: "browse NFTs from your smartphone",
    desc: "Our Krypto app is the easiest way to keep track of your assets when you’re on the go",
    button: "Download on IOS",
    img: "image_1.png",
  },
  {
    id: 3,
    subHeading: "24/7 Access",
    heading: "sell your NFTs from anywhere at any time",
    desc: "With our easy-to-use platform, you can buy or sell assets from anywhere in the world, at any time",
    button: "Get Started",
    img: "image_2.png",
  },
];

export default function Home() {
  const [clientWindowHeight, setClientWindowHeight] = useState("");

  const handleScroll = () => {
    setClientWindowHeight(window.scrollY);
  };

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  });

  return (
    <>
      <Head>
        <title>Krypto Responsive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-background font-outfit overflow-hidden relative z-20 pb-[50vh] md:pb-[25vh]">
        <Navbar bg={clientWindowHeight} />
        <div class="flex flex-col bg-background pt-[15vh] z-30">
          <Hero />
          <Featured />
          <div class="mt-24 md:pt-5 w-full text-text">
            <div class="xl:max-w-5xl mx-auto space-y-14 px-10 xl:px-0">
              {sections.map((section) => (
                <Section key={section.id} data={section} />
              ))}
            </div>
          </div>
          <Testimonial />
          <AreYouReady />
          <Footer />
        </div>
        <Image
          src="/ellipse_bg_1.png"
          alt="Ellipse Background"
          width={700}
          height={700}
          className="absolute -top-80 md:-top-96 md:-left-24 animate-pulse"
        />

        <Image
          src="/ellipse_bg_2.png"
          alt="Ellipse Background"
          width={450}
          height={450}
          className="absolute -right-48 top-80 animate-pulse"
        />
      </main>
    </>
  );
}
